apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minecraft-system

resources:
  - namespace.yaml
  - cockroachdb.yaml
  - redis.yaml
  - api-server.yaml
  - operator.yaml

commonLabels:
  environment: development
  app.kubernetes.io/part-of: minecraft-platform
