---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minecraft-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minecraft-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: minecraft-operator
    namespace: minecraft-system
